# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

plugin_name: pulp_cookbook
plugin_app_label: cookbook
plugin_snake: pulp_cookbook
plugin_caps: PULP_COOKBOOK
plugin_caps_short: COOKBOOK
plugin_camel: PulpCookbook
plugin_camel_short: Cookbook
plugin_dash: pulp-cookbook
plugin_dash_short: cookbook
black: True
check_commit_message: False
coverage: False
deploy_client_to_pypi: False
deploy_client_to_rubygems: False
deploy_daily_client_to_pypi: False
deploy_daily_client_to_rubygems: False
deploy_to_pypi: False
docs_test: False
pydocstyle: True
test_bindings: False
pypi_username: None
travis_notifications: None


